### ISSUE TITLE
Spell checking

### ISSUE THREAD

**Issue by Alectoria** [gustavobio/tpl#3]
Here is a case where it seems that the spell checking is having problems. 

Case 2. Pachycladon exile (includes spelling mistake in epithet)

    tpl.get("Pachycladon exile")

      id family genus species infraspecific.rank infraspecific.epithet authorship taxonomic.status.in.tpl   
     confidence.level source accepted.id name note original.search
     NA     NA    NA      NA                 NA                    NA         NA                      NA               NA      
        NA  NA   NA not found 
      Pachycladon exile

This species is not matched. But shouldn't the fuzzy matching that you implemented direct me to "Pachycladon exilis"?

    tpl.get("Pachycladon exilis")

     id       family       genus species infraspecific.rank infraspecific.epithet authorship  
     taxonomic.status.in.tpl confidence.level source accepted.id name note original.search
     tro-100358993 Brassicaceae Pachycladon  exilis (Heenan) Heenan & A.D.Mitch. Accepted                  
     L TRO  Pachycladon exilis      Pachycladon exilis

Thanks again for your effort!

**Comment by gustavobio** [comment]
Hello,

There is an argument to control how conservative the suggestion algorithm should be (the default is 0.9 with values close to 1 being extremely conservative). Depending on the length of the string this could match only names one substitution away from the misspelled one. You can fine tune the algorithm by using a lower value:

> tpl.get("Pachycladon exile", suggestion.distance = 0.85)
             id       family       genus species infraspecific.rank infraspecific.epithet                   authorship
1 tro-100358993 Brassicaceae Pachycladon  exilis                                          (Heenan) Heenan & A.D.Mitch.
  taxonomic.status.in.tpl confidence.level source accepted.id               name           note   original.search
1                Accepted                L    TRO             Pachycladon exilis was misspelled Pachycladon exile

The function is very conservative by default because lower values may match different taxa with similar names.

Thank you for using the package!

**Comment by Alectoria** [comment]
Ah, that makes sense! I totally overlooked that argument.
Thanks for the explanation!
